apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-fbmv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-wyyu-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-fbmv@sha256:47b078281a0a623e47195955b72c771f1516a74c2de91fe77d5711a2d016c626
        name: my-python
        resources: {}
status: {}
